server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/users
        - id: eureka-server
          uri: ${EUREKA_SERVER_URI:http://eureka:8761}
          predicates:
            - Path=/eureka/**
          filters:
            - RedirectTo=302, http://localhost:8761/
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 2
        sliding-window-size: 4
        sliding-window-type: count_based
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      userServiceCB:
        timeout-duration: 1s
        cancel-running-future: true